FROM node:alpine AS development

ENV NODE_ENV development
ENV PORT=3001

WORKDIR /app
COPY ./package.json .
COPY ./exirain-header-0.0.28.tgz .
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE ${PORT}

CMD ["npm", "run", "dev"]
